-- Florify: схема таблиц для Supabase.
-- Открой Supabase Dashboard -> SQL Editor -> New query, вставь этот файл целиком и нажми Run.
-- Anon/publishable ключ не имеет прав на DDL, поэтому создать таблицы можно только так
-- (или через Supabase CLI: supabase db push).

create table if not exists orders (
  id bigint generated by default as identity primary key,
  flowers text,
  budget int,
  delivery_date text,
  address text,
  client_name text,
  client_phone text,
  channel text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists clients (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists inventory (
  id bigint generated by default as identity primary key,
  flower_name text,
  quantity int not null default 0
);

create table if not exists write_offs (
  id bigint generated by default as identity primary key,
  flower_name text,
  quantity int,
  reason text,
  created_at timestamptz not null default now()
);

-- Доступ только для залогиненных сотрудников (Supabase Auth, роль authenticated).
-- Anon-ключ публичен (его отдаёт /api/config), поэтому без входа данные недоступны.
-- Пользователей создавать в Dashboard -> Authentication -> Users -> Add user,
-- а публичную регистрацию отключить: Authentication -> Sign In / Providers -> Allow new users to sign up = off.
-- Файл можно запускать повторно: старые политики с полным доступом для anon удаляются.

alter table orders enable row level security;
alter table clients enable row level security;
alter table inventory enable row level security;
alter table write_offs enable row level security;

drop policy if exists "orders_anon_all" on orders;
drop policy if exists "clients_anon_all" on clients;
drop policy if exists "inventory_anon_all" on inventory;
drop policy if exists "write_offs_anon_all" on write_offs;

drop policy if exists "orders_staff_all" on orders;
create policy "orders_staff_all" on orders for all to authenticated using (true) with check (true);

drop policy if exists "clients_staff_all" on clients;
create policy "clients_staff_all" on clients for all to authenticated using (true) with check (true);

drop policy if exists "inventory_staff_all" on inventory;
create policy "inventory_staff_all" on inventory for all to authenticated using (true) with check (true);

drop policy if exists "write_offs_staff_all" on write_offs;
create policy "write_offs_staff_all" on write_offs for all to authenticated using (true) with check (true);
