-- Florify: схема базы для Supabase.
-- Открой Supabase Dashboard -> SQL Editor -> New query, вставь этот файл целиком и нажми Run.
-- Файл можно запускать повторно: он ничего не удаляет из данных, только добавляет
-- недостающие таблицы/колонки и пересоздаёт функции и политики.

-- ============ таблицы ============

create table if not exists orders (
  id bigint generated by default as identity primary key,
  flowers text,
  budget int,
  delivery_date text,            -- дата/время как написал клиент («завтра к 18:00»)
  address text,
  client_name text,
  client_phone text,
  channel text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists clients (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists inventory (
  id bigint generated by default as identity primary key,
  flower_name text,
  quantity int not null default 0
);

create table if not exists write_offs (
  id bigint generated by default as identity primary key,
  flower_name text,
  quantity int,
  reason text,
  created_at timestamptz not null default now()
);

-- v2: реальная дата доставки, состав по позициям, связь с клиентом
alter table orders add column if not exists delivery_on date;          -- день доставки
alter table orders add column if not exists delivery_time time;        -- время доставки (местное)
alter table orders add column if not exists items jsonb not null default '[]'::jsonb; -- [{"flower":"Роза","qty":25}]
alter table orders add column if not exists client_id bigint references clients(id) on delete set null;
alter table orders add column if not exists updated_at timestamptz not null default now();

-- v2: закупочная цена (₸ за штуку) и стоимость списания на момент списания
alter table inventory add column if not exists purchase_price int not null default 0;
alter table write_offs add column if not exists unit_cost int not null default 0;

-- v2: история смены статусов — для аналитики скорости и опозданий
create table if not exists order_status_history (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  status text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid default auth.uid()
);

create index if not exists orders_delivery_on_idx on orders (delivery_on);
create index if not exists orders_client_id_idx on orders (client_id);
create index if not exists order_status_history_order_idx on order_status_history (order_id);

-- ============ триггеры ============

-- Телефон к единому виду: только цифры, казахстанская 8 в начале -> 7
create or replace function norm_phone(p text) returns text
language sql immutable as $$
  select case
    when d = '' then null
    when length(d) = 11 and left(d, 1) = '8' then '7' || substr(d, 2)
    when length(d) = 10 then '7' || d
    else d
  end
  from (select regexp_replace(coalesce(p, ''), '\D', '', 'g') as d) s
$$;

-- Заказ сам привязывается к клиенту по телефону; нового клиента создаёт автоматически
create or replace function orders_link_client() returns trigger
language plpgsql as $$
declare
  cid bigint;
begin
  new.updated_at := now();
  if norm_phone(new.client_phone) is null then
    return new;
  end if;
  if tg_op = 'UPDATE' and new.client_phone is not distinct from old.client_phone and new.client_id is not null then
    return new;
  end if;
  select id into cid from clients where norm_phone(phone) = norm_phone(new.client_phone) order by id limit 1;
  if cid is null then
    insert into clients (name, phone) values (coalesce(nullif(new.client_name, ''), 'Без имени'), new.client_phone)
    returning id into cid;
  elsif new.client_name is not null and new.client_name <> '' then
    update clients set name = new.client_name where id = cid and (name is null or name = '' or name = 'Без имени');
  end if;
  new.client_id := cid;
  return new;
end $$;

drop trigger if exists orders_link_client on orders;
create trigger orders_link_client before insert or update on orders
  for each row execute function orders_link_client();

-- Каждая смена статуса записывается в историю
create or replace function orders_log_status() returns trigger
language plpgsql as $$
begin
  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into order_status_history (order_id, status) values (new.id, new.status);
  end if;
  return new;
end $$;

drop trigger if exists orders_log_status on orders;
create trigger orders_log_status after insert or update of status on orders
  for each row execute function orders_log_status();

-- Привязать уже существующие заказы к клиентам (повторный запуск безопасен)
update orders set client_phone = client_phone where client_id is null and client_phone is not null;

-- Старым заказам — стартовая запись «new» в истории на момент создания
insert into order_status_history (order_id, status, changed_at)
  select o.id, 'new', o.created_at from orders o
  where not exists (select 1 from order_status_history h where h.order_id = o.id);

-- ============ атомарные операции со складом ============
-- Считаем остаток в базе, а не в браузере: два сотрудника одновременно не затрут друг друга.

create or replace function adjust_stock(item_id bigint, delta int) returns int
language sql as $$
  update inventory set quantity = greatest(0, quantity + delta) where id = item_id returning quantity
$$;

-- Списание и уменьшение остатка — одной транзакцией: либо оба, либо ничего
create or replace function write_off(p_flower text, p_qty int, p_reason text) returns void
language plpgsql as $$
declare
  cost int;
begin
  if p_qty is null or p_qty < 1 then
    raise exception 'Количество должно быть больше нуля';
  end if;
  update inventory set quantity = greatest(0, quantity - p_qty)
    where flower_name = p_flower
    returning purchase_price into cost;
  insert into write_offs (flower_name, quantity, reason, unit_cost)
    values (p_flower, p_qty, p_reason, coalesce(cost, 0));
end $$;

revoke execute on function adjust_stock(bigint, int) from public, anon;
revoke execute on function write_off(text, int, text) from public, anon;
grant execute on function adjust_stock(bigint, int) to authenticated;
grant execute on function write_off(text, int, text) to authenticated;

-- ============ доступ (RLS) ============
-- Доступ только для залогиненных сотрудников (Supabase Auth, роль authenticated).
-- Anon-ключ публичен (его отдаёт /api/config), поэтому без входа данные недоступны.
-- Пользователей создавать в Dashboard -> Authentication -> Users -> Add user,
-- а публичную регистрацию отключить: Authentication -> Sign In / Providers -> Allow new users to sign up = off.

alter table orders enable row level security;
alter table clients enable row level security;
alter table inventory enable row level security;
alter table write_offs enable row level security;
alter table order_status_history enable row level security;

drop policy if exists "orders_anon_all" on orders;
drop policy if exists "clients_anon_all" on clients;
drop policy if exists "inventory_anon_all" on inventory;
drop policy if exists "write_offs_anon_all" on write_offs;

drop policy if exists "orders_staff_all" on orders;
create policy "orders_staff_all" on orders for all to authenticated using (true) with check (true);

drop policy if exists "clients_staff_all" on clients;
create policy "clients_staff_all" on clients for all to authenticated using (true) with check (true);

drop policy if exists "inventory_staff_all" on inventory;
create policy "inventory_staff_all" on inventory for all to authenticated using (true) with check (true);

drop policy if exists "write_offs_staff_all" on write_offs;
create policy "write_offs_staff_all" on write_offs for all to authenticated using (true) with check (true);

drop policy if exists "status_history_staff_all" on order_status_history;
create policy "status_history_staff_all" on order_status_history for all to authenticated using (true) with check (true);
