-- Florify: схема таблиц для Supabase.
-- Открой Supabase Dashboard -> SQL Editor -> New query, вставь этот файл целиком и нажми Run.
-- Anon/publishable ключ не имеет прав на DDL, поэтому создать таблицы можно только так
-- (или через Supabase CLI: supabase db push).

create table if not exists orders (
  id bigint generated by default as identity primary key,
  flowers text,
  budget int,
  delivery_date text,
  address text,
  client_name text,
  client_phone text,
  channel text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists clients (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists inventory (
  id bigint generated by default as identity primary key,
  flower_name text,
  quantity int not null default 0
);

create table if not exists write_offs (
  id bigint generated by default as identity primary key,
  flower_name text,
  quantity int,
  reason text,
  created_at timestamptz not null default now()
);

-- В приложении нет авторизации (один магазин, все экраны открыты всем, у кого есть
-- ссылка), поэтому RLS включаем, но даём anon-ключу полный доступ ко всем 4 таблицам.
-- Это соответствует текущему поведению прототипа, но не подходит для реальных клиентских
-- данных без отдельного слоя аутентификации.

alter table orders enable row level security;
alter table clients enable row level security;
alter table inventory enable row level security;
alter table write_offs enable row level security;

drop policy if exists "orders_anon_all" on orders;
create policy "orders_anon_all" on orders for all using (true) with check (true);

drop policy if exists "clients_anon_all" on clients;
create policy "clients_anon_all" on clients for all using (true) with check (true);

drop policy if exists "inventory_anon_all" on inventory;
create policy "inventory_anon_all" on inventory for all using (true) with check (true);

drop policy if exists "write_offs_anon_all" on write_offs;
create policy "write_offs_anon_all" on write_offs for all using (true) with check (true);
